---

- name: add mesosphere repository
  yum:
    name: http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present
- name: install packages
  yum:
    name: mesos, marathon
    state: present
- name: set zookeeper connection string
  copy: content="{{ mesos_.zookeeper_connection_string }}" dest=/etc/mesos/zk
- name: set zookeeper quorum
  copy: content="{{ mesos.zookeeper_quorum }}" dest=/etc/mesos-master/quorum
- name: set mesos master hostname
  copy: content="{{ ansible_host }}" dest=/etc/mesos-master/hostname
  notify:
  - stop mesos slave
  - disable mesos slave
  - restart mesos master
  - restart marathon

